### PR TITLE
Fix status bar not having the correct style under iOS 10

### LINKED ISSUE #57: Status bar not tinting properly under iOS 10
b

### PR DESCRIPTION
**Pull request by 3lvis**
Fixes #57

### CODE REVIEW

**Comment by 3lvis** [comment]
Any ideas on how to unit test this?

**Comment by elland** [comment]
Missing the whole screenshot/gif thing?

Unit test: how can you unit test UI? 😢

**Comment by 3lvis** [comment]
I thought it was obvious since here you can see what we want vs what we have.

https://github.com/bakkenbaeck/Viewer/issues/57

**Comment by 3lvis** [comment]
Screenshot of fix:

screen shot 2016-09-29 at 11 54 17

**Comment by elland** [comment]
Sorry, I didn't see the reference to the Issue. 🙈

Ship it?!

**Comment by 3lvis** [comment]
Thanks! One day we'll do UI automatic testing, and that day is not today.

**Pull request merged**
