### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by 3lvis**
Drafted a quick logo for this project. Better than nothing :D

### CODE REVIEW

**Comment by elland** [comment]
Hmm, not sure what it's supposed to be, but it looks… a bit weird. Smiling mouth with a whole in it. 🙈

**Comment by 3lvis** [comment]
Should be an eye with the shape of a V.

**Comment by elland** [comment]
I would've never guessed that D:

**Comment by elland** [comment]
I'd go with just a V there, no need for more.

**Comment by 3lvis** [comment]
I guess we can always iterate on it :). Gonna keep it as a start.

**Comment by elland** [comment]
Is replacing the symbol with a letter difficult? 🤔

**Pull request merged**
