### PR TITLE
Fixed issue with zoom working all weird.

### PR DESCRIPTION
**Pull request by elland**

### CODE REVIEW

**Comment by askeland** [comment]
This will make all images zoom to the image center and breaks the functionality of the zoom. It's not the zoom itself that is weird, it is the image/content bounds of the scrollview that are not set correctly

**Comment by elland** [comment]
@askeland yeah, looking into the bound situation now, do you have any idea where it's breaking? Regarding ignoring touch location, that's how I assumed it should behave, zooming in on where the user taps for a simple 2x zoom feels out of place.

**Comment by askeland** [comment]
I fixed this in the Jottacloud Photos app, but we got a little detatched from this code because of cast support with more... added the code in #122 👍

**Comment by 3lvis** [comment]
Closing in favor of https://github.com/bakkenbaeck/Viewer/pull/122

**Pull request closed without merging**
